USE MODELOS_PREDITIVOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SP_INPUT_RESULTADOS_MODELO_PREDITIVO' AND TYPE = 'P')
	BEGIN
		DROP PROCEDURE SP_INPUT_RESULTADOS_MODELO_PREDITIVO
	END
GO

CREATE PROCEDURE SP_INPUT_RESULTADOS_MODELO_PREDITIVO
AS

TRUNCATE TABLE PREVISOES_INADIMPLENCIA

INSERT INTO PREVISOES_INADIMPLENCIA
SELECT
A.NUMERO_CONTRATO,
A.DATA_ASSINATURA_CONTRATO,
A.TIPO_FINANCIAMENTO,
A.TAXA_AO_ANO,
A.PZ_FINANCIAMENTO,
A.CIDADE_CLIENTE,
A.ESTADO_CLIENTE,
A.RENDA_MENSAL_CLIENTE,
A.QT_PC_ATRASO,
A.QT_DIAS_PRIM_PC_ATRASO,
A.QT_TOTAL_PC_PAGAS,
A.VL_TOTAL_PC_PAGAS,
A.QT_PC_PAGA_EM_DIA,
A.QT_DIAS_MIN_ATRASO,
A.QT_DIAS_MAX_ATRASO,
A.QT_DIAS_MEDIA_ATRASO,
A.VALOR_FINANCIAMENTO,
A.VALOR_PARCELA,
A.IDADE_DATA_ASSINATURA_CONTRATO,
B.PREVISOES,
B.PROBABILIDADES
FROM EXTRACAO_DADOS_SISTEMA A(NOLOCK)
INNER JOIN RESULTADOS_INTERMEDIARIOS B(NOLOCK) ON (B.NUMERO_CONTRATO = A.NUMERO_CONTRATO)

GO