USE MODELOS_PREDITIVOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'PREVISOES_INADIMPLENCIA' AND TYPE = 'U')
	BEGIN
		DROP TABLE PREVISOES_INADIMPLENCIA
	END
GO


CREATE TABLE PREVISOES_INADIMPLENCIA(
	NUMERO_CONTRATO					INTEGER			NULL,
	DATA_ASSINATURA_CONTRATO		DATE			NULL,
	TIPO_FINANCIAMENTO				VARCHAR(20)		NULL,
	TAXA_AO_ANO						NUMERIC(10,2)	NULL,
	PZ_FINANCIAMENTO				INTEGER			NULL,
	CIDADE_CLIENTE					VARCHAR(40)		NULL,
	ESTADO_CLIENTE					VARCHAR(02)		NULL,
	RENDA_MENSAL_CLIENTE			NUMERIC(10,2)	NULL,
	QT_PC_ATRASO					INTEGER			NULL,
	QT_DIAS_PRIM_PC_ATRASO			INTEGER			NULL,
	QT_TOTAL_PC_PAGAS				INTEGER			NULL,
	VL_TOTAL_PC_PAGAS				NUMERIC(10,2)	NULL,
	QT_PC_PAGA_EM_DIA				INTEGER			NULL,
	QT_DIAS_MIN_ATRASO				INTEGER			NULL,
	QT_DIAS_MAX_ATRASO				INTEGER			NULL,
	QT_DIAS_MEDIA_ATRASO			INTEGER			NULL,
	VALOR_FINANCIAMENTO				NUMERIC(12,2)	NULL,
	VALOR_PARCELA					NUMERIC(12,2)	NULL,
	IDADE_DATA_ASSINATURA_CONTRATO	INTEGER			NULL,
	PREVISOES						VARCHAR(03)		NULL,
	PROBABILIDADES					NUMERIC(12, 2)	NULL
) 

GO