USE MODELOS_PREDITIVOS
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE NAME =  'RESULTADOS_INTERMEDIARIOS' AND TYPE = 'U')
	BEGIN
		DROP TABLE RESULTADOS_INTERMEDIARIOS
	END
GO

CREATE TABLE RESULTADOS_INTERMEDIARIOS(
NUMERO_CONTRATO		INTEGER NOT NULL,
PREVISOES			VARCHAR(03) NOT NULL,
PROBABILIDADES		NUMERIC(12,2) NOT NULL
)

GO
